// export const patients = [
//   {
//     id: "RE",
//     name: "Ralph Edwards",
//     age: 35,
//     gender: "M",
//     avatar: "/placeholder.svg?height=40&width=40",
//     reason: "Wrist Fracture Surgery",
//     schedule: {
//       date: "Tue, 19 Mar 2024",
//       time: "2:00 PM",
//     },
//     email: "ralph@gmail.com",
//     phone: "+1 212 456 7890",
//     status: "Current",
//     priority: "High",
//     assignedDoctor: "Dr. Daniel McAdams",
//     emergencyContact: {
//       name: "Gia Edwards",
//       relation: "Spouse",
//       phone: "+1 212 456 2345",
//     },
//     vitals: {
//       bloodPressure: "132/87",
//       temperature: "100.4",
//       heartRate: "82/79",
//       oxygenSaturation: "95",
//       height: "5.10",
//       weight: "74",
//     },
//     medicalRecords: [
//       { date: "2024-03-15", diagnosis: "Wrist Fracture", treatment: "Surgery Scheduled" },
//       { date: "2023-11-10", diagnosis: "Sprained Ankle", treatment: "Rest and Ice" },
//     ],
//     medications: [
//       { name: "Ibuprofen", dosage: "400mg", frequency: "Every 6 hours" },
//       { name: "Acetaminophen", dosage: "500mg", frequency: "Every 4-6 hours as needed" },
//     ],
//     labResults: [
//       { date: "2024-03-14", test: "Complete Blood Count", result: "Normal" },
//       { date: "2024-03-14", test: "X-Ray", result: "Wrist Fracture Confirmed" },
//     ],
//     appointmentHistory: [
//       { date: "2024-03-15", doctor: "Dr. Daniel McAdams", reason: "Wrist Fracture Consultation" },
//       { date: "2023-11-10", doctor: "Dr. Sarah Johnson", reason: "Ankle Sprain Follow-up" },
//     ],
//   },
//   {
//     id: "JS",
//     name: "John Smith",
//     age: 37,
//     gender: "Male",
//     avatar: "/placeholder.svg?height=40&width=40",
//     reason: "Hypertension and Asthma",
//     schedule: {
//       date: "Mon, 18 Mar 2024",
//       time: "2:30 PM",
//     },
//     status: "Current",
//     priority: "Medium",
//     email: "john.smith@example.com",
//     phone: "+1 212 555 1234",
//     assignedDoctor: "Dr. Sarah Johnson",
//     emergencyContact: {
//       name: "Mary Smith",
//       relation: "Wife",
//       phone: "+1 212 555 5678",
//     },
//     vitals: {
//       bloodPressure: "140/90",
//       temperature: "98.6",
//       heartRate: "75/80",
//       oxygenSaturation: "97",
//       height: "5.11",
//       weight: "80",
//     },
//     medicalRecords: [
//       { date: "2024-02-20", diagnosis: "Hypertension", treatment: "Prescribed ACE inhibitors" },
//       { date: "2023-12-05", diagnosis: "Asthma", treatment: "Inhaler prescribed" },
//     ],
//     medications: [
//       { name: "Lisinopril", dosage: "10mg", frequency: "Once daily" },
//       { name: "Albuterol", dosage: "2 puffs", frequency: "As needed" },
//     ],
//     labResults: [
//       { date: "2024-02-20", test: "Blood Pressure", result: "140/90 mmHg" },
//       { date: "2024-02-20", test: "Lung Function Test", result: "Mild Obstruction" },
//     ],
//     appointmentHistory: [
//       { date: "2024-02-20", doctor: "Dr. Sarah Johnson", reason: "Hypertension Follow-up" },
//       { date: "2023-12-05", doctor: "Dr. Michael Lee", reason: "Asthma Diagnosis" },
//     ],
//   },
//   {
//     id: "RB",
//     name: "Robert Brown",
//     age: 67,
//     gender: "Male",
//     avatar: "/placeholder.svg?height=40&width=40",
//     reason: "Diagnosis Test for Diabetes Type 2",
//     schedule: {
//       date: "Sat, 16 Mar 2024",
//       time: "11:00 AM",
//     },
//     status: "New",
//     priority: "Medium",
//     email: "robert.brown@example.com",
//     phone: "+1 212 555 9876",
//     assignedDoctor: "Dr. Emily Chen",
//     emergencyContact: {
//       name: "Susan Brown",
//       relation: "Daughter",
//       phone: "+1 212 555 4321",
//     },
//     vitals: {
//       bloodPressure: "138/88",
//       temperature: "98.8",
//       heartRate: "72/76",
//       oxygenSaturation: "96",
//       height: "5.9",
//       weight: "85",
//     },
//     medicalRecords: [
//       { date: "2024-03-16", diagnosis: "Suspected Diabetes Type 2", treatment: "Pending Test Results" },
//       { date: "2023-09-30", diagnosis: "High Cholesterol", treatment: "Diet and Exercise Recommended" },
//     ],
//     medications: [{ name: "Atorvastatin", dosage: "20mg", frequency: "Once daily" }],
//     labResults: [
//       { date: "2024-03-16", test: "Fasting Blood Glucose", result: "Pending" },
//       { date: "2023-09-30", test: "Lipid Panel", result: "High LDL Cholesterol" },
//     ],
//     appointmentHistory: [
//       { date: "2024-03-16", doctor: "Dr. Emily Chen", reason: "Diabetes Type 2 Screening" },
//       { date: "2023-09-30", doctor: "Dr. Michael Lee", reason: "Annual Check-up" },
//     ],
//   },
//   {
//     id: "MJ",
//     name: "Mary Jones",
//     age: 42,
//     gender: "Female",
//     avatar: "/placeholder.svg?height=40&width=40",
//     reason: "Kidney Stone",
//     schedule: {
//       date: "Fri, 15 Mar 2024",
//       time: "7:50 PM",
//     },
//     status: "Current",
//     priority: "High",
//     email: "mary.jones@example.com",
//     phone: "+1 212 555 7890",
//     assignedDoctor: "Dr. Michael Lee",
//     emergencyContact: {
//       name: "David Jones",
//       relation: "Husband",
//       phone: "+1 212 555 0123",
//     },
//     vitals: {
//       bloodPressure: "120/80",
//       temperature: "99.1",
//       heartRate: "80/84",
//       oxygenSaturation: "98",
//       height: "5.6",
//       weight: "65",
//     },
//     medicalRecords: [
//       { date: "2024-03-15", diagnosis: "Kidney Stone", treatment: "Pain Management and Hydration" },
//       { date: "2023-07-20", diagnosis: "Urinary Tract Infection", treatment: "Antibiotics Prescribed" },
//     ],
//     medications: [
//       { name: "Tamsulosin", dosage: "0.4mg", frequency: "Once daily" },
//       { name: "Acetaminophen", dosage: "500mg", frequency: "Every 6 hours as needed for pain" },
//     ],
//     labResults: [
//       { date: "2024-03-15", test: "CT Scan", result: "5mm Kidney Stone Detected" },
//       { date: "2024-03-15", test: "Urinalysis", result: "Blood in Urine" },
//     ],
//     appointmentHistory: [
//       { date: "2024-03-15", doctor: "Dr. Michael Lee", reason: "Kidney Stone Treatment" },
//       { date: "2023-07-20", doctor: "Dr. Sarah Johnson", reason: "UTI Follow-up" },
//     ],
//   },
//   {
//     id: "WT",
//     name: "William Taylor",
//     age: 28,
//     gender: "Male",
//     avatar: "/placeholder.svg?height=40&width=40",
//     reason: "Hand Fracture",
//     schedule: {
//       date: "Mon, 11 Mar 2024",
//       time: "8:00 PM",
//     },
//     status: "Discharged",
//     priority: "Low",
//     email: "william.taylor@example.com",
//     phone: "+1 212 555 3456",
//     assignedDoctor: "Dr. Amanda White",
//     emergencyContact: {
//       name: "Elizabeth Taylor",
//       relation: "Mother",
//       phone: "+1 212 555 7890",
//     },
//     vitals: {
//       bloodPressure: "118/78",
//       temperature: "98.4",
//       heartRate: "68/72",
//       oxygenSaturation: "99",
//       height: "6.0",
//       weight: "75",
//     },
//     medicalRecords: [
//       { date: "2024-03-11", diagnosis: "Hand Fracture", treatment: "Cast Applied" },
//       { date: "2023-11-05", diagnosis: "Sprained Wrist", treatment: "Wrist Brace and Rest" },
//     ],
//     medications: [{ name: "Ibuprofen", dosage: "600mg", frequency: "Every 6 hours as needed for pain" }],
//     labResults: [
//       { date: "2024-03-11", test: "X-Ray", result: "Fracture of 5th Metacarpal" },
//       { date: "2024-03-11", test: "Complete Blood Count", result: "Normal" },
//     ],
//     appointmentHistory: [
//       { date: "2024-03-11", doctor: "Dr. Amanda White", reason: "Hand Fracture Treatment" },
//       { date: "2023-11-05", doctor: "Dr. Daniel McAdams", reason: "Wrist Sprain Follow-up" },
//     ],
//   },
// ]

// export const patientCategories = [
//   { name: "All Patients", count: 120 },
//   { name: "Current Patients", count: 80 },
//   { name: "New Patients", count: 20 },
//   { name: "Discharged Patients", count: 40 },
//   { name: "High Priority", count: 10 },
// ]

